services:
  lightcpverifier:
    build: .
    container_name: LightCPVerifier
    privileged: true              # go-judge 需要
    shm_size: "16g"                # 建议>=2G
    environment:
      PORT: "8081"                # orchestrator API 端口
      GJ_ADDR: "http://127.0.0.1:5050"
      JUDGE_WORKERS: "8"          # orchestrator 并发
      GJ_PARALLELISM: "8"         # go-judge 并发
    volumes:
      - ./problems:/app/problems
      - ./submissions:/app/submissions
      - ./data:/app/data          # 用于结果/缓存
    ports:
      - "8081:8081"
    restart: unless-stopped
